---
title: "Item 1"
author: "Rafael Felipe Bressan"
date: "10 de novembro de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r inicio, echo = FALSE}
# Case do Econometric Games
library(tidyverse)
library(knitr)
library(kableExtra)
library(stargazer)

load("dados_econometric_games.RData")
```

```{r estados}
uf_simbolos <- tribble(~uf, ~simbolo,
                       11 , "RO",
                       12 , "AC",
                       13 , "AM",
                       14 , "RR",
                       15 , "PA",
                       16 , "AP",
                       17 , "TO",
                       21 , "MA",
                       22 , "PI",
                       23 , "CE",
                       24 , "RN",
                       25 , "PB",
                       26 , "PE",
                       27 , "AL",
                       28 , "SE",
                       29 , "BA",
                       31 , "MG",
                       32 , "ES",
                       33 , "RJ",
                       35 , "SP",
                       41 , "PR",
                       42 , "SC",
                       43 , "RS",
                       50 , "MS",
                       51 , "MT",
                       52 , "GO",
                       53 , "DF",)
```

```{r descritivas1, results = "asis"}
descritivas <- coorte_00 %>% 
  filter(matricula != 0) %>% 
  mutate(prop = matricula / nv) %>% 
  select(nv, matricula, prop) %>% 
  gather(key = variavel, value = valor) %>% 
  group_by(variavel) %>% 
  summarise(media = mean(valor), mediana = median(valor), desv_p = sd(valor))  
descritivas[, 1] <- c("Matrícula", "Nasc. Vivos", "Proporção")  
kable(descritivas,
      format = "latex",
      digits = 3,
      col.names = c("Variável", "Média", "Mediana", "Desv. Pad.")) 

stargazer(descritivas, summary = FALSE,
          digits = 4,
          header = FALSE,
          rownames = FALSE)

coorte_00 %>% 
  select(nv, matricula) %>% 
  stargazer(header = FALSE,
            digits = 4,
            title = "Estatísticas descritivas para nascidos vivos em 2000 e matrículas em 2010.")
```

```{r boxplots}
box <- coorte_00 %>% 
  filter(matricula != 0) %>% 
  mutate(prop = matricula / nv) %>% 
  left_join(uf_simbolos, by = "uf")

ggplot(box, aes(x = simbolo, y = prop, color = simbolo)) +
  geom_boxplot() +
  labs(title = "Proporção de Matrícula / NV por UF",
       y = "Proporção (matricula / nv)",
       x = "UF") +
  theme_classic()
```

```{r scatter}
scatter <- coorte_00 %>% 
  filter(matricula != 0 & matricula < 50000) %>% 
  mutate(prop = nv / matricula,
         uf = as.factor(uf))

ggplot(scatter, aes(x = matricula, y = nv, color = uf)) +
  geom_point() +
  labs(title = "Scatter Plot",
       y = "Nascidos Vivos em 2000",
       x = "Matrículas em 2010",
       caption = "Obs: retirados os municípios com mais de 50.000 matrículas") +
  guides(color = guide_legend(title = "UF")) +
  scale_color_viridis_d()
```

```{r regressao, results = "asis"}
df_junto00 <- coorte_00 %>% 
  left_join(esf_00, by = "idmun")
modelo <- lm(matricula ~ esf + nv, data = df_junto00)

stargazer(modelo,
          title = "Impacto da presença de ESF nas matrículas ao 10 anos.",
          header = FALSE)
```

```{r scatter_esf}
scatter_esf <- df_junto00 %>% 
  filter(matricula != 0 & matricula < 50000) %>% 
  mutate(prop = nv / matricula,
         esf = as.factor(esf))

ggplot(scatter_esf, aes(x = nv, y = matricula, color = esf)) +
  geom_point() +
  labs(title = "Scatter Plot",
       y = "Matrículas em 2010",
       x = "Nascidos Vivos em 2000",
       caption = "Obs: retirados os municípios com mais de 50.000 matrículas") +
  guides(color = guide_legend(title = "ESF")) +
#  scale_color_viridis_d() +
  theme_classic()
```