---
title: "Item 2"
author: "Rafael Felipe Bressan"
date: "10 de novembro de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(knitr)
library(kableExtra)
library(stargazer)
load("dados_econometric_games.RData")
```

```{r estados}
uf_simbolos <- tribble(~uf, ~estado,
                       11 , "RO",
                       12 , "AC",
                       13 , "AM",
                       14 , "RR",
                       15 , "PA",
                       16 , "AP",
                       17 , "TO",
                       21 , "MA",
                       22 , "PI",
                       23 , "CE",
                       24 , "RN",
                       25 , "PB",
                       26 , "PE",
                       27 , "AL",
                       28 , "SE",
                       29 , "BA",
                       31 , "MG",
                       32 , "ES",
                       33 , "RJ",
                       35 , "SP",
                       41 , "PR",
                       42 , "SC",
                       43 , "RS",
                       50 , "MS",
                       51 , "MT",
                       52 , "GO",
                       53 , "DF",)
```

```{r dados}
# 2000
esf_00 %>% 
  left_join(coorte_00,
            by = c("idmun", "ano")) -> a2000
       
# 2005
esf_05 %>% 
  left_join(coorte_05,
            by = c("idmun", "ano")) -> a2005

bind_rows(a2000,a2005) %>% 
  left_join(uf_simbolos, by = "uf") %>% 
  mutate(ano = as.factor(ano),
         estado = as.factor(estado)) -> dados_item2
```


```{r dif-in-dif, results='asis'}
reg1 <- lm(matricula ~ nv + esf + ano + estado + esf*ano, 
           data = dados_item2)
sum1 <- summary(reg1) # o coeficiente 'did' é o que dá o efeito dif in dif
stargazer(reg1,
          header = FALSE,
          title = "Regressão de Diferenças em Diferenças (2005 - 2000)",
          single.row = TRUE)
```

```{r scatter_esf}
df_junto05 <- coorte_05 %>% 
  left_join(esf_05, by = "idmun")
scatter_esf <- df_junto05 %>% 
  filter(matricula != 0 & matricula < 50000) %>% 
  mutate(prop = nv / matricula,
         esf = as.factor(esf))

ggplot(scatter_esf, aes(x = nv, y = matricula, color = esf)) +
  geom_point() +
  labs(title = "Scatter Plot",
       y = "Matrículas em 2015",
       x = "Nascidos Vivos em 2005",
       caption = "Obs: retirados os municípios com mais de 50.000 matrículas") +
  guides(color = guide_legend(title = "ESF")) +
#  scale_color_viridis_d() +
  theme_classic()
```