---
title: "Item 4"
author: "Rafael Felipe Bressan"
date: "10 de novembro de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r inicio, echo = FALSE}
# Case do Econometric Games
library(tidyverse)
library(knitr)
library(kableExtra)
library(stargazer)

dados_4 <- readRDS("modelo_4.RDS")
  
dados_4 %>% 
  mutate(esf_antes = lag(esf)) %>% 
  filter(ano %in% c(2000,2005)) -> modelo_4
```

```{r estados}
uf_simbolos <- tribble(~uf, ~estado,
                       11 , "RO",
                       12 , "AC",
                       13 , "AM",
                       14 , "RR",
                       15 , "PA",
                       16 , "AP",
                       17 , "TO",
                       21 , "MA",
                       22 , "PI",
                       23 , "CE",
                       24 , "RN",
                       25 , "PB",
                       26 , "PE",
                       27 , "AL",
                       28 , "SE",
                       29 , "BA",
                       31 , "MG",
                       32 , "ES",
                       33 , "RJ",
                       35 , "SP",
                       41 , "PR",
                       42 , "SC",
                       43 , "RS",
                       50 , "MS",
                       51 , "MT",
                       52 , "GO",
                       53 , "DF",)
```

```{r modelo4, results = "asis"}

modelo_4 %>% 
  left_join(uf_simbolos,
            by = "uf") %>% 
  mutate(estado = as.factor(estado),
           ano = as.factor(ano)) %>% 
  gather(key = "bla",
         value = "matricula",
         c(matricula_10,matricula_15)) %>%
  gather(key = "nb",
         value = "nv",
         c(nv_05,nv_00)) %>% 
  select(-c(nb,bla)) -> modelo_4

modelo_4 %>% 
  distinct(municipio, uf, ano, .keep_all = T) -> modelo_4


modelo <- lm(matricula~esf_antes+nv+estado+ano+ano*esf_antes, data = modelo_4)

stargazer(modelo,
          header = FALSE,
          title = "Impacto da ESF antes do nascimento",
          single.row = TRUE)
```